"""add permissions

Revision ID: 10451b721888
Revises: a2e3d0111331
Create Date: 2023-09-27 17:56:04.123406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10451b721888'
down_revision: Union[str, None] = 'a2e3d0111331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('permission', sa.String(), nullable=False))
    op.drop_column('subscription', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('subscription', 'permission')
    # ### end Alembic commands ###
