"""fix payment methods

Revision ID: 900a7a4bd299
Revises: 214dd9906e2f
Create Date: 2023-09-29 14:58:24.777853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900a7a4bd299'
down_revision: Union[str, None] = '214dd9906e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_method', sa.Column('card_type', sa.String(), nullable=True))
    op.add_column('payment_method', sa.Column('first_numbers', sa.Integer(), nullable=True))
    op.add_column('payment_method', sa.Column('last_numbers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_method', 'last_numbers')
    op.drop_column('payment_method', 'first_numbers')
    op.drop_column('payment_method', 'card_type')
    # ### end Alembic commands ###
