"""currency nullable False

Revision ID: ae3e3c32bcaf
Revises: ee0e4f4fb3a4
Create Date: 2023-09-27 21:32:35.318353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3e3c32bcaf'
down_revision: Union[str, None] = 'ee0e4f4fb3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
