"""add currency

Revision ID: ee0e4f4fb3a4
Revises: 10451b721888
Create Date: 2023-09-27 21:29:51.877046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0e4f4fb3a4'
down_revision: Union[str, None] = '10451b721888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'currency')
    # ### end Alembic commands ###
