@startuml to be

== Автоплатеж ==

autonumber

Scheduler -> TransacionsDB: Раз в сутки делает выборку по всем подпискам \n у которых автоплатеж True и дата окончания < 24ч

TransacionsDB --> Scheduler: Списки [payment_method_id, value, currency, plan]

Scheduler -> UserSubscriptionsQueue: Создаем UUID подписки и Добавить в очередь [payment_method_id, value, currency, plan]

UserSubscriptionsQueue -> UserSubscriptionsWorker: Передать сообщене о подписке

UserSubscriptionsWorker -> UserSubscriptionsWorker: Создаем UserSubscriptions с UUID полученным из очереди

UserSubscriptionsWorker -> TransacionsDB: Сохраняем запись в UserSubscriptions

alt Успешно сохранили

TransacionsDB --> UserSubscriptionsWorker: Ok

else Запись уже есть

TransacionsDB --> UserSubscriptionsWorker: Error

end

par

UserSubscriptionsWorker -> PaymentsQueue: Добаваить в очередь UserSubscriptions

UserSubscriptionsWorker --> UserSubscriptionsQueue: Ok

end

PaymentsQueue -> PaymentsWorker: 

alt Платеж есть

PaymentsWorker -> TransacionsDB: Проверяем есть ли платеж у этой подписки

PaymentsWorker --> PaymentsQueue: Ок

else Платежа нет

PaymentsWorker -> ExternalPaymentService: Делаем запрос на списание средств в \n metadata пишем UUID UserSubscriptions

ExternalPaymentService --> PaymentsWorker: Ok Waiting for capture

PaymentsWorker -> PaymentsWorker: Создаем Payments с \n kassa_payment_id и user_subscriptions_id

PaymentsWorker -> TransacionsDB: Сохраняем Pyaments

TransacionsDB --> PaymentsWorker: Ok

PaymentsWorker --> PaymentsQueue: Ок

end

@enduml