@startuml to be

== Юзер оформляет подписку ==

autonumber

actor User

User -> BillingAPI: Запрос на офрмление подписки

BillingAPI -> BillingAPI: Проверяет токен юзера

BillingAPI -> TransactionsDB: Проверяем есть ли такая подписка и активна ли она

TransactionsDB --> BillingAPI: Ок

BillingAPI -> TransactionsDB: Запрос на действующую подписку

TransactionsDB --> BillingAPI: Ок

alt Подписка есть

BillingAPI -> TransactionsDB: Устанавливаем следующую подписку

TransactionsDB --> BillingAPI: Ок

BillingAPI -> ExternalPaymentService: Создаем ссылку для оплаты для новой карты с метадата отмена платежа и стоимостью 1 рубль и сохранением способа оплаты

ExternalPaymentService --> BillingAPI: Получаем id_payment

BillingAPI -> TransactionsDB: Сохраняем (UserPaymentMethod,PaymentMethod) с id_payment и статусом panding

TransactionsDB --> BillingAPI: Ок

else Подписки нет

BillingAPI -> TransactionsDB: Создаем подписку

TransactionsDB --> BillingAPI: Ок

BillingAPI -> ExternalPaymentService: Создаем ссылку для оплаты для новой карты с метадата без отмены платежа и стоимостью полписки и сохранением способа оплаты

ExternalPaymentService --> BillingAPI: Получаем id_payment

BillingAPI -> TransactionsDB: Сохраняем (UserPaymentMethod,PaymentMethod) и Payments с id_payment с статусом panding

TransactionsDB --> BillingAPI: Ок

end


BillingAPI --> User: Редирект на страницу оплаты

User -> ExternalPaymentService: Вводит данные карты. Запрос на списание средств

par Паралельное выполнение

ExternalPaymentService --> User: Редирект на страницу со статусом оплаты

ExternalPaymentService -> BillingAPI: Уведомление о совершенном платеже (вебхук) из metadata получаем user_id, plan

end

BillingAPI -> TransactionsDB: Сохраняем детали платежа, план подписки, срок действия и payment_method.id

TransactionsDB --> BillingAPI: Ok

par Паралельное выполнение

BillingAPI --> ExternalPaymentService: HTTP status 200 Ok

BillingAPI -> Auth: Меняем права пользователя

end

Auth --> BillingAPI: Ok

BillingAPI -> Notifications: Отправить уведомление юзеру о подписке

par

Notifications --> BillingAPI: Ok

Notifications -> User: Уведомление

end

@enduml